### PR TITLE
Create 006.frag

### PR DESCRIPTION
**Pull request by muellerfx**

### CODE REVIEW

**Comment by edap** [comment]
Hallo Felix, welcome on board ;) I suppose this is a new shader/ I think it would make sense to add a link in the menu, add a small image (check the other examples) and maybe add a description to this pull request so that it is easier for the reviewer to understand what's going on.

If you do not know how to do it, just asks ;)

**Comment by muellerfx** [comment]
Hello Davide, 
thanks for your message. 
I could not add an image to the shaders folder. I need to have push access for that. 
After I got access I will change my commit.

**Comment by edap** [comment]
Ah ok, cool. Then let's wait for it. Maybe it would also make sense, to add a short section in the Readme, about how to add an example, so that it's easier for the next person that wants upload a shader?

**Comment by muellerfx** [comment]
Sounds good to add some description how to add a new shader to the page and make an category entry to the menu. I will care about it after my commit.

**Pull request closed without merging**
